[window]
decorations = "None"
opacity = 0.85
blur = true
padding = { x = 4, y = 4 }
dynamic_padding = false

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0
builtin_box_drawing = true

# Colors (Gruvbox Material Hard Dark)
[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[colors.cursor]
text = "#1d2021"
cursor = "#d4be98"

[colors.selection]
text = "#1d2021"
background = "#d4be98"

[colors.normal]
black   = "#32302f"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#32302f"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

