[window]
decorations = "None"
opacity = 0.85
blur = true
padding = { x = 4, y = 4 }
dynamic_padding = false

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0
builtin_box_drawing = true

#Dracula-inspired neon
[colors.primary]
background = "0x18181F"
foreground = "0xf8f8f2"

[colors.cursor]
text = "0x44475a"
cursor = "0xf8f8f2"

[colors.normal]
black   = "0x18181F"
red     = "0xEA51B2"
green   = "0xEBFF87"
yellow  = "0x00F769"
blue    = "0x62D6E8"
magenta = "0xB45BCF"
cyan    = "0xA1EFE4"
white   = "0xE9E9F4"

[colors.bright]
black   = "0x626483"
red     = "0xEA51B2"
green   = "0xEBFF87"
yellow  = "0x00F769"
blue    = "0x62D6E8"
magenta = "0xB45BCF"
cyan    = "0xA1EFE4"
white   = "0xF7F7FB"

[colors.selection]
background = "0x44475a"
text = "0xf8f8f2"

[cursor.style]
shape = "Block"
blinking = "Off"

[scrolling]
history = 10000
multiplier = 3

